### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [MarioDena/MDmini#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by MarioDena** [comment]
I updated the README with a screenshot and also added some basic instructions.

Thank you for your interest.

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/803

**Comment by MarioDena** [comment]
@unixorn Well, thank you man I hope it's useful for someone out there. Cheers!
